env:
  global:
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
language: generic
services:
  - docker
sudo: required

before_install:
  - openssl aes-256-cbc -K $encrypted_11e05a66f615_key -iv $encrypted_11e05a66f615_iv -in travis-service-account.json.enc -out travis-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file travis-service-account.json
  - gcloud config set project koran-259415
  - gcloud config set compute/zone asia-southeast1-a
  - gcloud container clusters get-credentials koran-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t cglotr/koran-server ./server

script:
  - docker run cglotr/koran-server go test -v

deploy:
  on:
    branch: master
  provider: script
  script: bash ./deploy.sh
