START TRANSACTION;
CREATE TABLE user (
  id    INT         NOT NULL AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(50) NOT NULL,
  CONSTRAINT UNIQUE KEY (email)
);
INSERT INTO migration (version_name) VALUES ("v003");
COMMIT;
