export { default as colors } from './colors'
export { default as dimensions } from './dimensions'
export { default as durations } from './durations'
export { default as keys } from './keys'
export { default as suras } from './suras'
