apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: koran-arikama-co-tls
spec:
  commonName: arikama.co
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: koran-arikama-co
