apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-server
spec:
  replicas: 1
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - env:
          - name: MYSQL_DATABASE
            value: koran
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                key: MYSQL_PASSWORD
                name: secret-mysql-password
          image: cglotr/koran-server
          name: server
          ports:
            - containerPort: 8080
